config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resource :reviews, only: [:show]
  get "my-profile", to: "users#show"
  get "my-reviews", to: "reviews#index"
  resources :users, param: :nickname, only: [:show] do
    resources :reviews
  end

  resources :reviews, except: [:index] do
    resources :comments
  end

  namespace "api" do
    namespace "v1" do
      resources :reviews, only: [] do
        resources :comments, only: %i[create destroy update index]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review, validate: true
  belongs_to :user, validate: true
  validates :text, presence: true
  default_scope { order(created_at: :asc) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, validate: true
  default_scope { order(created_at: :desc) }
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :title, :text, :rating, presence: true
  paginates_per 6
  has_many :comments, dependent: :destroy

  def self.finished_reviews
    where(is_draft: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  def to_param
    nickname
  end
  has_one_attached :avatar

  has_many :reviews, dependent: :destroy
  has_many :comments

  validates :nickname, uniqueness: true, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      expose :comments, -> { fetch_comments }
      expose :comment, decorate: lambda { |comment|
        authorize! comment
        CommentDecorator.new(comment)
      }

      def index
        render json: comments
      end

      def create
        comment.review = Review.find(params[:review_id])
        if comment.save
          render json: comment, serializer: CommentSerializer
        else
          render json: comment.errors, status: :unprocessable_entity
        end
      end

      def destroy
        comment.destroy
        render json: { status: 200 }
      end

      private

      def comment_params
        params.require(:comment).permit(:text).merge(user_id: current_user.id)
      end

      def fetch_comments
        comments = Review.find(params[:review_id]).comments
        authorize! comments
        comments
      end
    end
  end
end

app/controllers/application_controller.rb
module Draper
  def policy_for(record:, **opts)
    record = record.model while record.is_a?(Draper::Decorator)
    super(record: record, **opts)
  end
end

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  prepend Draper

  def current_user
    UserDecorator.decorate(super) unless super.nil?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[nickname avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[nickname avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose :comments, lambda {
    authorize! fetch_comments
    CommentDecorator.decorate_collection(fetch_comments)
  }
  expose :comment, decorate: lambda { |comment|
    authorize! comment
    CommentDecorator.new(comment)
  }

  def create
    comment.user_id = current_user.id
    comment.review = Review.find(params[:review_id])
    comment.save
    redirect_to review_path(comment.review)
  end

  def destroy
    comment.destroy
    redirect_to review_path(comment.review)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def fetch_comments
    Review.find(params[:review_id]).comments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose :reviews, -> { ReviewDecorator.decorate_collection(fetch_popular_reviews(3)) }

  def fetch_popular_reviews(count)
    Review.finished_reviews.reorder(views: :desc).take(count)
  end
end

app/controllers/my_reviews_controller.rb
class MyReviewsController < ApplicationController
  expose :reviews, -> { ReviewDecorator.decorate_collection(fetch_reviews) }
  expose :review, decorate: ->(review) { ReviewDecorator.new(review) }
  REVIEW_PARAMS = %i[created_at is_draft rating].freeze

  def index
    render "reviews/index"
  end

  private

  def fetch_reviews
    current_user.reviews(review_params).page(params[:page])
  end

  def review_params
    params.permit(*REVIEW_PARAMS)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  expose :reviews, lambda {
    authorize! fetch_reviews
    ReviewDecorator.decorate_collection(fetch_reviews)
  }
  expose :review, decorate: lambda { |review|
    authorize! review
    ReviewDecorator.new(review)
  }
  before_action :authenticate_user!

  REVIEW_PARAMS = %i[title text rating is_draft].freeze

  def show
    review.increment_views
  end

  def create
    review.user = current_user
    if review.save
      redirect_to review_path(review)
    else
      render :new
    end
  end

  def update
    if review.update(review_params)
      redirect_to review_path(review)
    else
      render :edit
    end
  end

  def destroy
    review.destroy
    redirect_to user_reviews_url(current_user)
  end

  private

  def review_params
    params.require(:review).permit(*REVIEW_PARAMS)
  end

  def fetch_reviews
    user.filtered_reviews(params).page(params[:page])
  end

  def user
    result = if params[:user_nickname].nil?
      current_user
    else
      User.find_by(nickname: params[:user_nickname])
    end
    UserDecorator.new(result)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose :user, -> { UserDecorator.new(fetch_user) }

  def show
  end

  def fetch_user
    return current_user if params[:nickname].nil?

    User.find_by(nickname: params[:nickname])
  end
end

app/views/comments/_comment.html.slim
.media.comment-box data-id = comment.id
  .media-left
    a href="#"
      img.img-responsive.user-photo src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" /
  .media-body
    h4.media-heading
      = comment.user.email
      span.float-right = comment.created_at_format
    p = comment.text
    - if allowed_to?(:destroy?, comment)
      = link_to 'Delete comment', api_v1_review_comment_path(review_id: review.id, id: comment.id), method: :delete, class: 'btn btn-danger', remote: true, :data => {id: comment.id, confirm: 'Are you sure?'}

app/views/comments/_form.html.slim
h2 Commment
= simple_form_for [review, review.comments.build] do |f|
	.form-group
 	= f.input :text, label: false, placeholder: "Text", input_html: {class: 'form-control'}, as: :text
	= f.button :submit, class: 'btn btn-primary mt-2'

app/views/comments/ajax/_form.html.slim
h2 Commment
= simple_form_for(review.comments.build, url: api_v1_review_comments_path(review_id: review.id), method: :post, remote: true) do |f|
	.form-group
 	= f.input :text, label: false, placeholder: "Text", input_html: {class: 'form-control'}, as: :text
	= f.button :submit, class: 'btn btn-primary mt-2'

app/views/home/index.html.slim
main[role="main"]
  .jumbotron
    .container
      h1.display-3
        | Hello, world!
      p
        | This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
      p
  .container
    h2 Popular reviews
    .row
      = render reviews

    hr
footer.container
  p
    | © 2019

app/views/layouts/application.html.slim
html
  head
    title BookReviews
    = csrf_meta_tags

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
body
  nav.navbar.navbar-expand-md.navbar-dark.shadow.bg-dark.fixed-top
    = link_to "Book Reviews", root_url, class: "navbar-brand"
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarsExampleDefault.collapse.navbar-collapse
      ul.navbar-nav
        - if user_signed_in?
          li.nav-item
            = link_to "My profile", my_profile_url, class: "nav-link"
          li.nav-item
            = link_to "My Reviews", my_reviews_url, class: "nav-link"
          li.nav-item
            = link_to "My Drafts", my_reviews_url(is_draft: true), class: "nav-link"
          li.nav-item
            = link_to "Edit my profile", edit_user_registration_url(current_user), class: "nav-link"
      form.form-inline.my-2.my-lg-0.mr-auto
        input.form-control.mr-sm-2[type="text" placeholder="Search" aria-label="Search"]
        button.btn.btn-outline-success.my-2.my-sm-0[type="submit"]
          | Search
      - if user_signed_in?
        = link_to "Create review", new_review_path, class: "btn btn-light mr-3"
      .form-inline.my-2.my-lg-0.mr-3
        - if user_signed_in?
          span.text-light> Hello,
          .text-light = current_user.nickname
          .font-weight-bold.d-inline.mr-2
          = link_to " Sign out", destroy_user_session_path, :method => :delete, class: "btn btn-outline-light"
        - else
          = link_to " Sign in", new_user_session_path, class: "btn text-light"
          = link_to " Sign up", new_user_registration_path, class: "btn btn-outline-light font-weight-light"
  .wrap
    = yield

app/views/reviews/_form.html.slim
= simple_form_for(review) do |f|
  .form-group
    = f.input :title, label: false, placeholder: "Title", input_html: { class: "form-control" }
  .form-group
    = f.input :text, label: false, placeholder: "Text", input_html: { class: "form-control" }, as: :text
  .form-group
    = f.input :rating, label: false, placeholder: "rating", input_html: { class: "form-control" }
  .form-check
    = f.check_box :is_draft, class: "form-check-input"
    = f.label :is_draft, "Черновик", class: "form-check-label"
  = f.button :submit, class: "btn btn-primary mt-2"

app/views/reviews/_review.html.slim
.col-md-4
  .shadow-sm.p-4.mb-4.rounded.review-wrap
    .float-right.text-muted
      => review.draft_display
      i class="fa fa-eye pr-1" aria-hidden="true"
      = review.views
    h4
      = review.short_title
    p
      = review.short_text
    p
      = review.formated_rating
    .crud-review-buttons
      = link_to "View details", review, class: "btn btn-secondary"
      - if user_signed_in? && allowed_to?(:modify?, review)
        = link_to "Edit", edit_review_path(review), class: "btn btn-primary"
        = link_to "Destroy", review, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/reviews/edit.html.slim
.container

  h1 Editing Review

  = render "form", review: review

  = link_to "Show", review
  = link_to "Back", user_reviews_url(current_user)

app/views/reviews/index.html.slim
.container

  h1 Reviews

  .row
    = render reviews

  = paginate reviews
  br

app/views/reviews/new.html.slim
.container
  h1 New Review

  = render "form", review: review

  = link_to "Back", user_reviews_url(current_user)

app/views/reviews/show.html.slim
.container
  .review
    .float-right.text-muted = review.draft_display
    h3 = review.title
    = review.text
    br
    = review.formated_rating
    br
    - if allowed_to?(:modify?, review)
      = link_to "Edit", edit_review_path(review), class: "btn btn-primary"

  = render review.comments

  = render "comments/ajax/form"

app/views/users/show.html.slim
.container.emp-profile
  form method="post" 
    .row
      .col-md-4
        .profile-img
          - if user.avatar.attached?
            = image_tag user.avatar, class: "rounded-circle"
      .col-md-6
        .profile-head
          h5
            = user.nickname
          h6
            = user.role
          p.proile-rating
            | Average rating :
            span => user.average_rating
          p.proile-rating
            | Standard deviation :
            span => user.standard_deviation
          ul#myTab.nav.nav-tabs role="tablist" 
            li.nav-item
              a#home-tab.nav-link.active aria-controls="home" aria-selected="true" data-toggle="tab" href="#home" role="tab"  About
            li.nav-item
              = link_to "Reviews", user_reviews_url(user), class: "nav-link"
      .col-md-2
        - if allowed_to?(:modify?, user)
          = link_to "Edit profile", edit_user_registration_url(current_user), class: "profile-edit-btn"
    .row
      .col-md-4
        .profile-work
          p Last reviews
          - user.last_reviews(3).each do |review|
            = link_to review.short_title, review_url(review)
            br
          p Popular reviews
          - user.popular_reviews(3).each do |review|
            = link_to review.short_title, review_url(review)
            br

      .col-md-8
        #myTabContent.tab-content.profile-tab
          #home.tab-pane.fade.show.active aria-labelledby="home-tab" role="tabpanel" 
            .row
              .col-md-6
                label Nickname
              .col-md-6
                p = user.nickname
            .row
              .col-md-6
                label Email
              .col-md-6
                p = user.email